-- The Postgres twin of store/sqlite/migrations/00006_chat_log.sql. Same three
-- tables, same columns, same indexes — only the spelling differs, so the migrate
-- tool can stay a table-for-table copier.
--
-- Only chat_message is partitioned, and only here: SQLite has no partitioning
-- and gets no retention, exactly as 00005 established for the ledger.
--
-- Unlike 00005 this rewrites nothing — chat_message is new and empty — so it is
-- an ordinary additive migration and needs no cutover.
--
-- See docs/adr/0003-chat-log.md.

-- +goose Up

-- Every bound below is a date cast to timestamptz, which is interpreted in the
-- session's TimeZone — and this cluster's is Europe/Malta. Without this line
-- 'YYYY-MM-DD'::timestamptz means 22:00 UTC the previous day, so each child
-- would sit two hours away from the UTC day it is named after: rows near
-- midnight UTC would silently land in chat_message_default (where retention can
-- never reach them, since only registered bounded partitions are expiry
-- candidates) and gopartman, which computes bounds in UTC, would report drift on
-- every child. 00005 records finding this the hard way; the trap is identical.
SET LOCAL TimeZone = 'UTC';

CREATE TABLE IF NOT EXISTS chat_message (
	id      BIGINT      GENERATED BY DEFAULT AS IDENTITY,
	-- ts is the timestamp of record and stays BIGINT unix seconds, one value
	-- copied straight across both backends (ADR-0001). ts_at is the same instant
	-- in the type gopartman can partition on. Nothing enforces the relationship:
	-- a stored generated column cannot be a partition key, an expression key
	-- would forbid the primary key outright, and a BEFORE INSERT trigger cannot
	-- fill it because tuple routing happens first — 00005 documents all three
	-- against the PG 18.4 binary we run. So every INSERT writes it, there is no
	-- DEFAULT to paper over a path that forgets, and a test checks every row.
	ts      BIGINT      NOT NULL,
	ts_at   TIMESTAMPTZ NOT NULL,
	room_id TEXT        NOT NULL,
	-- Twitch's own message id (the `id` tag). CLEARMSG targets it, which is the
	-- entire reason it is stored. It deliberately carries no UNIQUE constraint: a
	-- partitioned table's unique index must include the partition key, so the
	-- guarantee would degrade to "unique per day" — the same degradation that
	-- pushed ledger_ref out into its own table in 00004. The difference is that
	-- nothing here depends on uniqueness, so there is nothing to rescue: Twitch
	-- already guarantees it and the database need not re-prove it.
	msg_id  TEXT        NOT NULL,
	user_id TEXT        NOT NULL,
	-- Denormalized rather than joined from users, because users is written only
	-- by the economy (bot/economy.go) and is empty when the economy is off —
	-- wordle_wins and connections_wins set this precedent. It also makes the row
	-- carry the name as it was at the time, which is the right answer for an
	-- archive: people rename.
	login   TEXT        NOT NULL,
	display TEXT        NOT NULL,
	-- Raw, exactly as it arrived. removeEmotes can always recompute the stripped
	-- form from text + emotes; nothing recovers the original from the stripped
	-- one, so the archive keeps the version that cannot be reconstructed.
	text    TEXT        NOT NULL,
	emotes  TEXT        NOT NULL DEFAULT '',

	is_mod         BOOLEAN NOT NULL DEFAULT false,
	is_sub         BOOLEAN NOT NULL DEFAULT false,
	is_vip         BOOLEAN NOT NULL DEFAULT false,
	is_broadcaster BOOLEAN NOT NULL DEFAULT false,

	-- 0 = live, following the "0 = none" convention game_rounds.ends_at and
	-- ledger_opening.through_ts already use, so no reader has to handle NULL.
	-- The text is deliberately left intact: the moderation question is "what did
	-- they say that got them banned", and redacting it answers the one case this
	-- table exists for with a blank. Erasure requests are served by
	-- `chat-partition -purge-user`, which is a real delete.
	deleted_at BIGINT NOT NULL DEFAULT 0,
	deleted_by TEXT   NOT NULL DEFAULT '',  -- 'clearmsg' | 'clearchat' | ''

	-- A partitioned table's primary key must include every partitioning column,
	-- so "id is unique" weakens to "(id, ts_at) is unique". Academic — the ids
	-- come from one sequence — and invisible to Go.
	PRIMARY KEY (id, ts_at)
) PARTITION BY RANGE (ts_at);

-- The name matters to the character. gopartman's drain.PartitionData hardcodes
-- {parent}_default, and RegisterParent issues its own CREATE TABLE ... DEFAULT
-- which would collide with a differently-named one.
CREATE TABLE IF NOT EXISTS chat_message_default PARTITION OF chat_message DEFAULT;

-- Today plus the same 14-day premake window cmd/chat-partition asks gopartman
-- for.
--
-- The migration has to seed these itself. The bot starts writing the moment it
-- comes up, and the maintenance job does not run until 05:30 the following
-- morning; without them the first night of chat lands in chat_message_default,
-- which is invisible to retention until someone runs -backfill by hand. Seeding
-- the whole premake window rather than just today also means a bot that outlives
-- a stopped launchd agent keeps landing in bounded children for two weeks.
--
-- Names must match gopartman's grammar exactly ({parent}_YYYYMMDD, UTC day
-- start) or ImportExisting silently skips them — and a skipped partition is one
-- that never expires.
--
-- StatementBegin/End because goose splits a migration on ';' and this body is
-- full of them.
-- +goose StatementBegin
DO $$
DECLARE d date;
BEGIN
	FOR d IN
		SELECT generate_series((now() AT TIME ZONE 'UTC')::date,
		                       (now() AT TIME ZONE 'UTC')::date + 14,
		                       interval '1 day')::date
	LOOP
		EXECUTE format(
			'CREATE TABLE IF NOT EXISTS %I PARTITION OF chat_message FOR VALUES FROM (%L) TO (%L)',
			'chat_message_' || to_char(d, 'YYYYMMDD'), d::timestamptz, (d + 1)::timestamptz);
	END LOOP;
END $$;
-- +goose StatementEnd

-- Both are partitioned indexes: Postgres builds and maintains a local index on
-- every child, existing and future, so nothing has to remember to index a
-- partition gopartman creates at 05:30.
--
-- chat_message_user leads on user_id and carries ts_at so a moderation lookup
-- ("this person's last N lines") is one index scan per child in descending time
-- order.
CREATE INDEX IF NOT EXISTS chat_message_user ON chat_message (user_id, ts_at DESC);

-- chat_message_msg exists for CLEARMSG. The UPDATE that applies a tombstone
-- knows the message id but not when the message was sent, so it has no time
-- predicate to prune on and Appends across every child. That is ~90 index probes
-- at a 90-day horizon, each sub-millisecond, a handful of times per stream —
-- cheap enough that bounding it with a guessed time window would trade
-- correctness for nothing. MarkUserCleared, which does have a timestamp, passes
-- one and prunes.
CREATE INDEX IF NOT EXISTS chat_message_msg ON chat_message (msg_id);

-- The fold target, and the only chat history that outlives retention.
--
-- Written exclusively by cmd/chat-partition and never on the write path: this is
-- the ledger_opening pattern from 00004, not the accounts.balance one from
-- 00003. The consequence is that it counts only messages whose partition has
-- already been folded, so a user's true total is
--
--     chat_stats.messages + COUNT(*) FROM chat_message WHERE user_id = ...
--
-- and either half alone is an undercount. That seam is the price of keeping the
-- write path free of a second write; docs/adr/0003-chat-log.md argues it is
-- worth paying because nothing reads these totals at runtime.
--
-- Not partitioned, and never dropped.
CREATE TABLE IF NOT EXISTS chat_stats (
	user_id  TEXT   PRIMARY KEY,
	login    TEXT   NOT NULL,
	display  TEXT   NOT NULL,
	messages BIGINT NOT NULL DEFAULT 0,
	chars    BIGINT NOT NULL DEFAULT 0,
	first_ts BIGINT NOT NULL DEFAULT 0,  -- oldest folded message
	last_ts  BIGINT NOT NULL DEFAULT 0   -- newest folded message
);

-- Which chat_message partitions have been folded into chat_stats. The primary
-- key is the idempotency: a fold that died after COMMIT is indistinguishable
-- from one that finished, so the next pass skips it and drops the orphan rather
-- than counting it twice. Deliberately ours and not partman.partitions.status —
-- 00004 makes the same argument for ledger_folded, and coupling our totals to
-- another library's bookkeeping means a library upgrade can change what they
-- mean.
CREATE TABLE IF NOT EXISTS chat_folded (
	name       TEXT   PRIMARY KEY,
	from_ts    BIGINT NOT NULL,
	through_ts BIGINT NOT NULL,
	rows       BIGINT NOT NULL,
	folded_at  BIGINT NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS chat_folded;
DROP TABLE IF EXISTS chat_stats;
-- CASCADE takes the children with it; they are partitions, not data of their own.
DROP TABLE IF EXISTS chat_message CASCADE;
