-- The Postgres twin of store/sqlite/migrations/00001_baseline.sql. Same tables,
-- same columns, same indexes — only the spelling differs, so the migrate tool
-- can stay a table-for-table copier.
--
-- Timestamps stay BIGINT unix values rather than becoming timestamptz: one code
-- path across both backends, and a straight value copy at cutover.

-- +goose Up
CREATE TABLE IF NOT EXISTS commands (
	name     TEXT PRIMARY KEY,
	response TEXT   NOT NULL,
	cooldown BIGINT NOT NULL DEFAULT 0,
	min_role TEXT   NOT NULL DEFAULT 'everyone',
	count    BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS users (
	user_id   TEXT   PRIMARY KEY,
	login     TEXT   NOT NULL,
	display   TEXT   NOT NULL,
	last_seen BIGINT NOT NULL
);

-- BY DEFAULT, not ALWAYS: the one-shot migrate tool inserts explicit ids so
-- ledger row ids survive the copy, then resets the sequence past the max. With
-- ALWAYS those inserts would need an OVERRIDING clause every time.
CREATE TABLE IF NOT EXISTS ledger (
	id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id TEXT   NOT NULL,
	delta   BIGINT NOT NULL,
	reason  TEXT   NOT NULL,
	ref     TEXT,
	ts      BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS ledger_user ON ledger(user_id);

-- Idempotent channel-point crediting: a redemption id credits at most once. The
-- partial index ports verbatim — but note that Credit's ON CONFLICT has to
-- repeat the WHERE clause, or Postgres cannot infer this index.
CREATE UNIQUE INDEX IF NOT EXISTS ledger_ref ON ledger(ref) WHERE ref IS NOT NULL;

CREATE TABLE IF NOT EXISTS settings (
	key   TEXT PRIMARY KEY,
	value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS wordle_wins (
	user_id TEXT   PRIMARY KEY,
	login   TEXT   NOT NULL,
	display TEXT   NOT NULL,
	wins    BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS connections_wins (
	user_id TEXT   PRIMARY KEY,
	login   TEXT   NOT NULL,
	display TEXT   NOT NULL,
	wins    BIGINT NOT NULL DEFAULT 0
);

-- +goose Down
DROP TABLE IF EXISTS connections_wins;
DROP TABLE IF EXISTS wordle_wins;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS ledger;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS commands;
