-- Convert ledger to a table partitioned by day on ts_at.
--
-- This rewrites the whole table. Migrations run inside Open(), so it executes
-- when the new bot binary first starts -- at 17k rows that is milliseconds, but
-- deploy it as a cutover: stop the bot, mise run db:backup, mise run db:migrate,
-- verify, start.
--
-- See docs/adr/0002-ledger-retention-and-partitioning.md. The SQLite twin is a
-- documented no-op.

-- +goose Up

-- Every bound below is written as a date cast to timestamptz, which is
-- interpreted in the session's TimeZone -- and this cluster's is Europe/Malta.
-- Without this line 'YYYY-MM-DD'::timestamptz means 22:00 UTC the previous day,
-- so each child would sit two hours away from the UTC day it is named after:
-- rows near midnight UTC would silently land in the default partition (where
-- retention can never reach them, since only registered bounded partitions are
-- expiry candidates) and gopartman, which computes bounds in UTC, would report
-- drift on every child. Verified on PG 18.4; TestPartitionBoundsAreUTC pins it.
SET LOCAL TimeZone = 'UTC';

CREATE TABLE ledger_new (
	id      BIGINT      GENERATED BY DEFAULT AS IDENTITY,
	user_id TEXT        NOT NULL,
	delta   BIGINT      NOT NULL,
	reason  TEXT        NOT NULL,
	ref     TEXT,
	ts      BIGINT      NOT NULL,
	-- ts is the timestamp of record and stays BIGINT unix seconds, one value
	-- copied straight across both backends. ts_at is the same instant in the type
	-- gopartman can partition on. Nothing enforces the relationship: a stored
	-- generated column cannot be a partition key, an expression key would forbid
	-- the primary key outright, and a BEFORE INSERT trigger cannot fill it
	-- because tuple routing happens first. So every INSERT writes it, there is no
	-- DEFAULT to paper over a path that forgets, and a test checks every row.
	ts_at   TIMESTAMPTZ NOT NULL,
	-- A partitioned table's primary key must include every partitioning column,
	-- so "id is unique" weakens to "(id, ts_at) is unique". Academic -- the ids
	-- come from one sequence -- and invisible to Go.
	PRIMARY KEY (id, ts_at)
) PARTITION BY RANGE (ts_at);

-- The name matters to the character. drain.PartitionData hardcodes
-- {parent}_default, and RegisterParent issues its own CREATE TABLE ... DEFAULT
-- which would collide with a differently-named one.
CREATE TABLE ledger_default PARTITION OF ledger_new DEFAULT;

-- One child per day that has data, through today.
--
-- The migration has to create these itself: gopartman's provisioner only ever
-- builds {current} u {premake futures} u {default} and never reaches into the
-- past, and PartitionData records an anomaly rather than creating a partition it
-- cannot find. Anything left in the default partition is invisible to retention
-- forever.
--
-- Names must match gopartman's grammar exactly ({parent}_YYYYMMDD, UTC day
-- start) or ImportExisting silently Skips them -- and a skipped partition is one
-- that never expires.
-- StatementBegin/End because goose splits a migration on ';' and this body is
-- full of them. Without the markers it fails with "unterminated dollar-quoted
-- string", which at least fails loudly.
-- +goose StatementBegin
DO $$
DECLARE d date;
BEGIN
	FOR d IN
		SELECT generate_series(
			COALESCE((SELECT (to_timestamp(MIN(ts)) AT TIME ZONE 'UTC')::date FROM ledger),
			         (now() AT TIME ZONE 'UTC')::date),
			(now() AT TIME ZONE 'UTC')::date,
			interval '1 day')::date
	LOOP
		EXECUTE format(
			'CREATE TABLE IF NOT EXISTS %I PARTITION OF ledger_new FOR VALUES FROM (%L) TO (%L)',
			'ledger_' || to_char(d, 'YYYYMMDD'), d::timestamptz, (d + 1)::timestamptz);
	END LOOP;
END $$;
-- +goose StatementEnd

INSERT INTO ledger_new (id, user_id, delta, reason, ref, ts, ts_at)
SELECT id, user_id, delta, reason, ref, ts, to_timestamp(ts) FROM ledger;

DROP TABLE ledger;
ALTER TABLE ledger_new RENAME TO ledger;
-- Renaming the table does not rename the sequence it owns, so without this
-- \d ledger reports ledger_new_id_seq forever. Nothing breaks —
-- pg_get_serial_sequence resolves it either way — but "ledger_new" is a name
-- that only makes sense to someone reading this file. DROP TABLE ledger above
-- took the old ledger_id_seq with it, so the name is free.
ALTER SEQUENCE ledger_new_id_seq RENAME TO ledger_id_seq;

-- Recreated as a local index on each child. ledger_user is what Balance used
-- before the balance was materialized; it stays for ad-hoc history queries and
-- for the fold's per-user GROUP BY.
CREATE INDEX ledger_user ON ledger(user_id);

-- The copy carried explicit ids, so the sequence is still at 1. Without this the
-- first live Credit after the migration collides on the primary key.
SELECT setval(pg_get_serial_sequence('ledger', 'id'),
              COALESCE((SELECT MAX(id) FROM ledger), 0) + 1, false);

-- +goose Down

SET LOCAL TimeZone = 'UTC';

CREATE TABLE ledger_old (
	id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id TEXT   NOT NULL,
	delta   BIGINT NOT NULL,
	reason  TEXT   NOT NULL,
	ref     TEXT,
	ts      BIGINT NOT NULL
);

INSERT INTO ledger_old (id, user_id, delta, reason, ref, ts)
SELECT id, user_id, delta, reason, ref, ts FROM ledger;

-- CASCADE takes the children with it; they are partitions, not data of their own.
DROP TABLE ledger CASCADE;
ALTER TABLE ledger_old RENAME TO ledger;
ALTER SEQUENCE ledger_old_id_seq RENAME TO ledger_id_seq;
CREATE INDEX ledger_user ON ledger(user_id);

SELECT setval(pg_get_serial_sequence('ledger', 'id'),
              COALESCE((SELECT MAX(id) FROM ledger), 0) + 1, false);
