-- The Torch Maze replay log: every finished round, kept permanently.
--
-- maze_rounds carries everything needed to re-run a round, and maze_events
-- carries what happened, so a question like "how often does the last key decide
-- it" is a query rather than a re-simulation. The engine is deterministic — no
-- randomness anywhere — which is what makes a stored round genuinely replayable
-- rather than merely summarised.
--
-- NOT PARTITIONED, unlike chat_message in 00006, and deliberately so. A round is
-- at most a few dozen cycles times five players, so a busy stream writes a few
-- hundred rows a night where chat writes that many an hour. The decisive argument
-- is not volume though: partitioning exists here to enable retention, and this
-- table's whole purpose is that nothing is ever dropped from it. Partitioning it
-- would be all of that machinery — a default child, a premake window, gopartman
-- registration, a nightly agent, a folded-counts seam in every query — for none
-- of the benefit.
--
-- The Postgres twin is store/postgres/migrations/00008_maze_log.sql.

-- +goose Up

-- id is TEXT and generated by the bot ("<startedAtMillis>-<seed hex>"), not an
-- autoincrement. Rounds cannot overlap — there is one board stage — so the start
-- time is already unique, and a text key keeps this table out of the sequence
-- reset cmd/store-migrate has to do for ledger and chat_message after a cutover.
CREATE TABLE IF NOT EXISTS maze_rounds (
	id         TEXT PRIMARY KEY,
	room_id    TEXT    NOT NULL,
	seed       INTEGER NOT NULL,
	started_at INTEGER NOT NULL,
	ended_at   INTEGER NOT NULL,
	tick_ms    INTEGER NOT NULL,
	cycles     INTEGER NOT NULL DEFAULT 0,
	-- An end-reason wire value, or 'skipped' when a mod ran !skipgame. The engine
	-- has no such reason of its own and inventing one would ripple through the
	-- wire maps and every already-stored round, so it is an extra value here and
	-- written down rather than left as a mystery in a stats query.
	reason     TEXT    NOT NULL DEFAULT '',
	players    INTEGER NOT NULL DEFAULT 0,
	finishers  INTEGER NOT NULL DEFAULT 0,
	-- Empty when nobody got out, which is a real outcome rather than a missing one.
	winner_id      TEXT NOT NULL DEFAULT '',
	winner_login   TEXT NOT NULL DEFAULT '',
	winner_display TEXT NOT NULL DEFAULT '',
	-- The replay document: board, both configs, and the ordered submissions. The
	-- board is stored rather than regenerated from the seed for the reason
	-- internal/maze/persist.go already gives about resume, only stronger here — an
	-- archive read years and many redeploys later must not depend on the generator
	-- still producing byte-identical output.
	input      TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS maze_events (
	round_id TEXT    NOT NULL,
	seq      INTEGER NOT NULL,
	cycle    INTEGER NOT NULL,
	kind     TEXT    NOT NULL,
	seat     INTEGER NOT NULL DEFAULT -1,
	user_id  TEXT    NOT NULL DEFAULT '',
	login    TEXT    NOT NULL DEFAULT '',
	display  TEXT    NOT NULL DEFAULT '',
	-- Chat coordinate ('C4'), empty for the kinds that have no position. Writing
	-- the zero cell would record 'A1' — a real-looking board square — on every
	-- seats-locked and round-ended row.
	at       TEXT    NOT NULL DEFAULT '',
	n        INTEGER NOT NULL DEFAULT 0,
	reason   TEXT    NOT NULL DEFAULT '',
	-- No foreign key on round_id, matching every other table here: store-migrate
	-- copies table by table and states that copy order is readability rather than
	-- integrity. A key would make that order load-bearing, and SQLite has them off
	-- by default anyway, so the two backends would disagree about what is an error.
	PRIMARY KEY (round_id, seq)
);

CREATE INDEX IF NOT EXISTS maze_events_kind ON maze_events (kind, round_id);

-- +goose Down
DROP INDEX IF EXISTS maze_events_kind;
DROP TABLE IF EXISTS maze_events;
DROP TABLE IF EXISTS maze_rounds;
